### ISSUE TITLE
ASNField is too small

### ISSUE THREAD

**Issue by steffann** [20c/django-inet#9]
ASNField is a PositiveIntegerField, which means its range is from 0 to 2147483647 (2^31-1) because it is still stored as a signed integer in the database. An ASN is a unsigned 32-bit integer these days, and therefore has a range of 0 to 4294967295 (2^32-1). To be able to store all valid ASNs a PositiveBigIntegerField should be used.

**Comment by grizz** [comment]
I'm amazed that `PositiveIntegerField` is a 31bit number, but you're absolutely correct, and thank you for the catch and PR. :)
